# ✅ Nombre y puerto
spring.application.name=socialpagebackend
server.port=9090
server.error.include-stacktrace=ON_PARAM

# ✅ Configuración de base de datos (usa las variables de entorno)
spring.datasource.username=${pgUser}
spring.datasource.password=${pgPassword}
spring.datasource.url=${bdd}

# ✅ ESTRATEGIA FINAL DE CREACIÓN DE TABLAS
spring.jpa.hibernate.ddl-auto=update

# ⚠️ IMPORTANTE: desactiva carga automática de scripts
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# ✅ Dialecto y zona horaria
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=false

# ✅ Tamaño máximo de archivos
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
spring.servlet.multipart.enabled=true

# ✅ Seguridad
security.jwt.expiration-time=1800000

# ✅ Logging (si usas Logbook)
logging.level.org.zalando.logbook.Logbook=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

logbook.masking.enabled=true
logbook.obfuscate.headers=Authorization
logbook.obfuscate.parameters=password
logbook.obfuscate.body.patterns='"password": ".*"'
logbook.format.style=http
logbook.filter.enabled=true

# ✅ Logging archivo
logging.file=/logs/websocial.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# ✅ Meta Facebook
meta.graph-api.url=https://graph.facebook.com
meta.graph-api.page-id=622983367573605
meta.graph-api.page-access-token=EAAKZAlHkcS7gBOZ...
